version: "3"
services:
  grafana:
    image: grafana/grafana:latest-ubuntu
    deploy: 
      placement: 
        constraints: 
          - node.platform.os == linux
          - node.role == worker
          - node.hostname == worker-01
    restart: always
    ports:
      - 3003:3000
    networks:
      - monitoring
      - dmz
    volumes:
      - grafana-volume:/var/lib/grafana
      - /shared/telemetry/grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini

  influxdb:
    image: influxdb #Se recomienda usar version especifica
    deploy: 
      placement: 
        constraints: 
          - node.platform.os == linux
          - node.role == worker
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
      - dmz # due to ansible interactions
    volumes:
      - /shared/telemetry/influxdb:/var/lib/influxdb
      #- influxdb-volume:/var/lib/influxdb
    environment: # avoid error when reach X number of registries with one tag
      - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=1500000
      - INFLUXDB_DATA_MAX_VALUES_PER_TAG=0 
 

networks:
  monitoring:
  dmz:
    external: true
      
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
